version: '3.8'

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-blog-prod
    container_name: laravel-blog-app-prod
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
      - /var/www/vendor
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "80:80"
    # Note: No MySQL service - using RDS in production