version: '3.8'

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-blog
    container_name: laravel-blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
      - /var/www/vendor
    networks:
      - laravel
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-blog-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-blog-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - mysql

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local